CREATE TABLE "activity_tb" (
    "sig_id"     CHAR(15)     NOT NULL PRIMARY KEY,
    "name"       VARCHAR(127) NOT NULL,
    "appname"    VARCHAR(63)  NOT NULL,
    "scope"      VARCHAR(15)  NOT NULL DEFAULT "trans",
    "action"     VARCHAR(15)  NOT NULL,
    "log_append" VARCHAR(31),
    "desc"       VARCHAR(127)
);
-- count: 7

-- sig_id      || name       || appname || scope  || action || append || desc
T: '0x401ffed' || 'login'    || 'SMTP'  || 'sess' || 'log'
T: '0x405ffed' || 'upload'   || 'SMTP'  || 'sess' || 'log'
T: '0x401ffee' || 'login'    || 'IMAP'  || 'sess' || 'log'
T: '0x406ffee' || 'download' || 'IMAP'  || 'sess' || 'log'
T: '0x401ffef' || 'login'    || 'POP3'  || 'sess' || 'log'
T: '0x406ffef' || 'download' || 'POP3'  || 'sess' || 'log'

-- sig_id       || name               || appname   || scope   || action || append           || desc
T: '0x7ff0000'  || 'restful_activity' || 'Restful' || 'trans' || 'log'
-- '0x13ff0000' || 'restful'          || 'Restful' || 'trans' || 'log'  || '"success":true'
T: '0x150000'   || 'user_restful'     || 'Restful' || 'trans' || 'log'
T: '0x4150000'  || 'user_restful'     || 'Restful' || 'trans' || 'log'
T: '0x8150000'  || 'user_restful'     || 'Restful' || 'trans' || 'log'
T: '0xbff0000'  || 'restful'          || 'Restful' || 'trans' || 'log'
T: '0x4050000'  || 'upload'           || 'Restful' || 'trans' || 'log'
T: '0x4060000'  || 'download'         || 'Restful' || 'trans' || 'log'
T: '0x4010000'  || 'common_login'     || 'Restful' || 'trans' || 'log'  || '"success":true'
T: '0x8010000'  || 'common_login'     || 'Restful' || 'trans' || 'log'  || '"success":true'

-- sig_id       || name                       || appname || scope   || action       || append || desc
T: '0x71f0001'  || 'create_user_token'        || 'Box'   || 'trans' || 'new_ctx'
T: '0x71e0001'  || 'create_user_token_web'    || 'Box'   || 'trans' || 'new_ctx'
T: '0x71d0001'  || 'create_user_token_logout' || 'Box'   || 'trans' || 'new_ctx'
T: '0x4010001'  || 'login'                    || 'Box'   || 'trans' || 'login_log'
T: '0x8010001'  || 'login'                    || 'Box'   || 'trans' || 'log'
T: '0x4020001'  || 'logout'                   || 'Box'   || 'trans' || 'logout_log'
T: '0xc010001'  || 'login'                    || 'Box'   || 'trans' || 'log'
T: '0x810001'   || 'login'                    || 'Box'   || 'trans' || 'login_log'
T: '0x1c010001' || 'login'                    || 'Box'   || 'trans' || 'login_log'
T: '0x14010001' || 'login'                    || 'Box'   || 'trans' || 'login_log'
T: '0x24010001' || 'login'                    || 'Box'   || 'trans' || 'login_log'
T: '0x18010001' || 'oauth2_authorize'         || 'Box'   || 'trans' || 'login_log'
T: '0x8020001'  || 'logout'                   || 'Box'   || 'trans' || 'logout_log'
T: '0x81f0001'  || 'first_load'               || 'Box'   || 'trans' || 'log'
T: '0xc1f0001'  || 'item_list'                || 'Box'   || 'trans' || 'log'
T: '0x101f0001' || 'guest_first_load'         || 'Box'   || 'trans' || 'log'
T: '0x141f0001' || 'guest_folder_list'        || 'Box'   || 'trans' || 'log'
T: '0x181f0001' || 'mobile_folder_list'       || 'Box'   || 'trans' || 'log'
T: '0x1c1f0001' || 'wap_item_list'            || 'Box'   || 'trans' || 'log'
T: '0x201f0001' || 'get_items'                || 'Box'   || 'trans' || 'log'
T: '0x70050001' || 'create_mobile_upload'     || 'Box'   || 'trans' || 'new_ctx'
T: '0x14050001' || 'wap_upload_begin'         || 'Box'   || 'trans' || 'log'
T: '0x18050001' || 'upload'                   || 'Box'   || 'trans' || 'log'
T: '0xc060001'  || 'download'                 || 'Box'   || 'trans' || 'log'
T: '0x14060001' || 'download'                 || 'Box'   || 'trans' || 'log'
T: '0x18060001' || 'download'                 || 'Box'   || 'trans' || 'log'
T: '0x20060001' || 'download'                 || 'Box'   || 'trans' || 'log'
T: '0x4030001'  || 'view'                     || 'Box'   || 'trans' || 'log'
T: '0x8030001'  || 'view'                     || 'Box'   || 'trans' || 'log'
T: '0xc030001'  || 'view'                     || 'Box'   || 'trans' || 'log'
T: '0x4090001'  || 'unshare'                  || 'Box'   || 'trans' || 'log'
T: '0x8090001'  || 'unshare'                  || 'Box'   || 'trans' || 'log'
T: '0xc090001'  || 'share'                    || 'Box'   || 'trans' || 'log'
T: '0x10090001' || 'share'                    || 'Box'   || 'trans' || 'log'
T: '0x14090001' || 'share'                    || 'Box'   || 'trans' || 'log'
T: '0x18090001' || 'share'                    || 'Box'   || 'trans' || 'log'
T: '0x241f0001' || 'get_collab'               || 'Box'   || 'trans' || 'log'
T: '0x1c090001' || 'unshare'                  || 'Box'   || 'trans' || 'log'
T: '0x281f0001' || 'get_collab'               || 'Box'   || 'trans' || 'log'
T: '0x40b0001'  || 'move'                     || 'Box'   || 'trans' || 'log'
T: '0x40d0001'  || 'copy'                     || 'Box'   || 'trans' || 'log'
T: '0x4080001'  || 'delete'                   || 'Box'   || 'trans' || 'log'
T: '0x8080001'  || 'delete'                   || 'Box'   || 'trans' || 'log'
T: '0x80b0001'  || 'move'                     || 'Box'   || 'trans' || 'log'
T: '0x80d0001'  || 'copy'                     || 'Box'   || 'trans' || 'log'
T: '0x4070001'  || 'create'                   || 'Box'   || 'trans' || 'log'
T: '0x8070001'  || 'create'                   || 'Box'   || 'trans' || 'log'
T: '0xc070001'  || 'create'                   || 'Box'   || 'trans' || 'log'
T: '0x10070001' || 'create'                   || 'Box'   || 'trans' || 'log'
T: '0x2c1f0001' || 'service_error'            || 'Box'   || 'trans' || 'log'

-- sig_id       || name                    || appname   || scope   || action       || append || desc
T: '0x71f0002'  || 'create_user_token'     || 'Dropbox' || 'trans' || 'new_ctx'
T: '0x71e0002'  || 'create_user_token_web' || 'Dropbox' || 'trans' || 'new_ctx'
T: '0x4020002'  || 'logout'                || 'Dropbox' || 'trans' || 'logout_log'
T: '0x4010002'  || 'login'                 || 'Dropbox' || 'trans' || 'login_log'
T: '0x4030002'  || 'view'                  || 'Dropbox' || 'trans' || 'log'
T: '0x4090002'  || 'share_link'            || 'Dropbox' || 'trans' || 'log'
T: '0x8090002'  || 'share'                 || 'Dropbox' || 'trans' || 'log'
T: '0xc090002'  || 'unshare'               || 'Dropbox' || 'trans' || 'log'
-- '0x8060002'  || 'download_files'        || 'Dropbox' || 'trans' || 'log'
T: '0xc050002'  || 'create_advance_upload' || 'Dropbox' || 'trans' || 'new_ctx'
T: '0x10050002' || 'mobile_app_upload'     || 'Dropbox' || 'trans' || 'log'
T: '0x4080002'  || 'delete'                || 'Dropbox' || 'trans' || 'log'
T: '0x41f0002'  || 'browser_files'         || 'Dropbox' || 'trans' || 'log'
T: '0x8010002'  || 'mobile_web_login'      || 'Dropbox' || 'trans' || 'login_log'
T: '0x10060002' || 'mobile_app_download'   || 'Dropbox' || 'trans' || 'log'
T: '0xc060002'  || 'mobile_app_download'   || 'Dropbox' || 'trans' || 'log'
T: '0x10090002' || 'mobile_share'          || 'Dropbox' || 'trans' || 'log'
T: '0x8080002'  || 'mobile_app_delete'     || 'Dropbox' || 'trans' || 'log'
T: '0x610002'   || 'mobile_web_login'      || 'Dropbox' || 'trans' || 'login_log'
T: '0xc080002'  || 'mobile_web_delete'     || 'Dropbox' || 'trans' || 'log'
T: '0x4070002'  || 'create'                || 'Dropbox' || 'trans' || 'log'
T: '0x81f0002'  || 'browse'                || 'Dropbox' || 'trans' || 'log'
T: '0x14090002' || 'mobile_share_link'     || 'Dropbox' || 'trans' || 'log'
T: '0x10010002' || 'mobile_app_login'      || 'Dropbox' || 'trans' || 'login_log'
T: '0x18090002' || 'share'                 || 'Dropbox' || 'trans' || 'log'
T: '0x40b0002'  || 'move'                  || 'Dropbox' || 'trans' || 'log'
T: '0x80b0002'  || 'move'                  || 'Dropbox' || 'trans' || 'log'
T: '0x14010002' || 'web_login_fail'        || 'Dropbox' || 'trans' || 'log'

-- sig_id      || name        || appname      || scope   || action || append || desc
T: '0x4010004' || 'pre_login' || 'Salesforce' || 'trans' || 'log'
T: '0x8010004' || 'login'     || 'Salesforce' || 'trans' || 'log'
T: '0x4020004' || 'logout'    || 'Salesforce' || 'trans' || 'log'
T: '0x8050004' || 'upload'    || 'Salesforce' || 'trans' || 'log'
T: '0x8060004' || 'download'  || 'Salesforce' || 'trans' || 'log'
T: '0x8080004' || 'delete'    || 'Salesforce' || 'trans' || 'log'
T: '0x8030004' || 'view'      || 'Salesforce' || 'trans' || 'log'
T: '0x8090004' || 'share'     || 'Salesforce' || 'trans' || 'log'

-- sig_id       || name                          || appname        || scope   || action || append || desc
T: '0x4010005'  || 'pre_web_login_1'             || 'OneDrive_pro' || 'trans' || 'log'
T: '0x8010005'  || 'pre_web_login_2'             || 'OneDrive_pro' || 'trans' || 'log'
T: '0xc010005'  || 'app_pre_login'               || 'OneDrive_pro' || 'trans' || 'log'
T: '0x10010005' || 'app_login'                   || 'OneDrive_pro' || 'trans' || 'log'
T: '0x14010005' || 'web_login'                   || 'OneDrive_pro' || 'trans' || 'log'
T: '0x4020005'  || 'web_logout'                  || 'OneDrive_pro' || 'trans' || 'log'
T: '0x4060005'  || 'web_download'                || 'OneDrive_pro' || 'trans' || 'log'
T: '0x8060005'  || 'web_download'                || 'OneDrive_pro' || 'trans' || 'log'
T: '0x4080005'  || 'web_delete'                  || 'OneDrive_pro' || 'trans' || 'log'
T: '0x4050005'  || 'web_upload'                  || 'OneDrive_pro' || 'trans' || 'log'
T: '0x4090005'  || 'share'                       || 'OneDrive_pro' || 'trans' || 'log'
T: '0x8090005'  || 'share_link'                  || 'OneDrive_pro' || 'trans' || 'log'
T: '0x41f0005'  || 'browser_id_name_mapping'     || 'OneDrive_pro' || 'trans' || 'log'
T: '0xc090005'  || 'unshare'                     || 'OneDrive_pro' || 'trans' || 'log'
T: '0x4030005'  || 'view'                        || 'OneDrive_pro' || 'trans' || 'log'
T: '0x81f0005'  || 'app_file_update'             || 'OneDrive_pro' || 'trans' || 'log'
T: '0xc060005'  || 'app_file_download_or_upload' || 'OneDrive_pro' || 'trans' || 'log'

-- sig_id       || name                          || appname               || scope   || action          || append            || desc
T: '0x4010006'  || 'web_login'                   || 'Constcontact'        || 'trans' || 'log'
T: '0x4020006'  || 'logout'                      || 'Constcontact'        || 'trans' || 'log'
T: '0x8010006'  || 'pre_login'                   || 'Constcontact'        || 'trans' || 'log'
T: '0xc010006'  || 'login'                       || 'Constcontact'        || 'trans' || 'log'
T: '0x10010006' || 'login_fail'                  || 'Constcontact'        || 'trans' || 'log'

-- sig_id       || name                          || appname               || scope   || action          || append            || desc
T: '0x4010007'  || 'login'                       || 'Expensify'           || 'trans' || 'log'
T: '0x4020007'  || 'logout'                      || 'Expensify'           || 'trans' || 'log'

-- sig_id       || name                          || appname               || scope   || action          || append            || desc
T: '0x4010008'  || 'login'                       || 'Square'              || 'trans' || 'log'
T: '0x4020008'  || 'logout'                      || 'Square'              || 'trans' || 'log'

-- sig_id       || name                          || appname               || scope   || action          || append            || desc
T: '0x4020009'  || 'logout'                      || 'Mozy'                || 'trans' || 'log'
T: '0x4010009'  || 'login'                       || 'Mozy'                || 'trans' || 'log'
T: '0x4080009'  || 'delete'                      || 'Mozy'                || 'trans' || 'log'
T: '0x8010009'  || 'cli_login_1'                 || 'Mozy'                || 'trans' || 'log'
T: '0xc010009'  || 'cli_login'                   || 'Mozy'                || 'trans' || 'log'
T: '0x8060009'  || 'cli_download'                || 'Mozy'                || 'trans' || 'log'
T: '0x8050009'  || 'cli_upload'                  || 'Mozy'                || 'trans' || 'log'
T: '0x8080009'  || 'cli_delete'                  || 'Mozy'                || 'trans' || 'log'

-- sig_id       || name                          || appname               || scope   || action          || append            || desc
T: '0x401000a'  || 'login'                       || 'iCloud'              || 'trans' || 'log'
T: '0x402000a'  || 'logout'                      || 'iCloud'              || 'trans' || 'log'
T: '0x408000a'  || 'note_delete'                 || 'iCloud'              || 'trans' || 'log'
T: '0x407000a'  || 'note_create'                 || 'iCloud'              || 'trans' || 'log'
T: '0x405000a'  || 'upload'                      || 'iCloud'              || 'trans' || 'log'
T: '0x406000a'  || 'export_download'             || 'iCloud'              || 'trans' || 'log'
T: '0x806000a'  || 'direct_download'             || 'iCloud'              || 'trans' || 'log'
T: '0x808000a'  || 'delete'                      || 'iCloud'              || 'trans' || 'log'
T: '0x409000a'  || 'unshare'                     || 'iCloud'              || 'trans' || 'log'
T: '0x809000a'  || 'share'                       || 'iCloud'              || 'trans' || 'log'
T: '0x41f000a'  || 'mail'                        || 'iCloud'              || 'trans' || 'log'
T: '0x801000a'  || 'app_login'                   || 'iCloud'              || 'trans' || 'log'
T: '0xc1f000a'  || 'browser_file'                || 'iCloud'              || 'trans' || 'log'
T: '0x403000a'  || 'view'                        || 'iCloud'              || 'trans' || 'log'
T: '0x807000a'  || 'create'                      || 'iCloud'              || 'trans' || 'log'
T: '0x805000a'  || 'upload'                      || 'iCloud'              || 'trans' || 'log'
T: '0xc06000a'  || 'download'                    || 'iCloud'              || 'trans' || 'log'
T: '0x803000a'  || 'view'                        || 'iCloud'              || 'trans' || 'log'
T: '0xc05000a'  || 'upload'                      || 'iCloud'              || 'trans' || 'log'
T: '0xc01000a'  || 'login_validate'              || 'iCloud'              || 'trans' || 'log'
T: '0x1001000a' || 'web_login'                   || 'iCloud'              || 'trans' || 'log'           || '"success":true'
T: '0x1401000a' || 'web_login'                   || 'iCloud'              || 'trans' || 'log'           || '"success":false'

-- sig_id      || name                 || appname    || scope   || action          || append || desc
T: '0x71f000b' || 'create_user_token'  || 'OneDrive' || 'trans' || 'new_ctx'
T: '0x71e000b' || 'create_user_token'  || 'OneDrive' || 'trans' || 'new_ctx'
T: '0x72e000b' || 'cancel_download'    || 'OneDrive' || 'trans' || 'cancel_updown'
T: '0x401000b' || 'web_login'          || 'OneDrive' || 'trans' || 'login_log'
T: '0x402000b' || 'logout'             || 'OneDrive' || 'trans' || 'logout_log'
T: '0x408000b' || 'web_delete'         || 'OneDrive' || 'trans' || 'log'
T: '0x26000b'  || 'web_files_download' || 'OneDrive' || 'trans' || 'log'
T: '0x409000b' || 'web_share'          || 'OneDrive' || 'trans' || 'log'
T: '0x403000b' || 'web_view'           || 'OneDrive' || 'trans' || 'log'
T: '0x801000b' || 'app_login'          || 'OneDrive' || 'trans' || 'login_log'
T: '0x805000b' || 'app_upload'         || 'OneDrive' || 'trans' || 'log'
-- '0x81f000b' || 'app_modify'         || 'OneDrive' || 'trans' || 'log'
T: '0xc06000b' || 'app_download'       || 'OneDrive' || 'trans' || 'log'
-- '0x803000b' || 'app_view'           || 'OneDrive' || 'trans' || 'log'

-- sig_id       || name                    || appname       || scope   || action       || append           || desc
T: '0x71f000c'  || 'create_user_token'     || 'GoogleDrive' || 'trans' || 'new_ctx'
T: '0x71e000c'  || 'create_user_token_web' || 'GoogleDrive' || 'trans' || 'new_ctx'
T: '0x401000c'  || 'login'                 || 'GoogleDrive' || 'trans' || 'login_log'
T: '0x801000c'  || 'login'                 || 'GoogleDrive' || 'trans' || 'log'
T: '0xc01000c'  || 'login'                 || 'GoogleDrive' || 'trans' || 'login_log'
T: '0x1001000c' || 'login'                 || 'GoogleDrive' || 'trans' || 'login_log'  || '"success":true'
T: '0x402000c'  || 'logout'                || 'GoogleDrive' || 'trans' || 'logout_log'
T: '0x41f000c'  || 'first_load'            || 'GoogleDrive' || 'trans' || 'log'
T: '0xc1f000c'  || 'folder_list'           || 'GoogleDrive' || 'trans' || 'log'
T: '0x101f000c' || 'folder_list'           || 'GoogleDrive' || 'trans' || 'log'
T: '0x405000c'  || 'start_upload'          || 'GoogleDrive' || 'trans' || 'log'
T: '0x805000c'  || 'upload'                || 'GoogleDrive' || 'trans' || 'log'
T: '0xc05000c'  || 'upload'                || 'GoogleDrive' || 'trans' || 'log'
-- '0x1005000c' || 'upload'                || 'GoogleDrive' || 'trans' || 'log'
T: '0x1005000c' || 'upload'                || 'GoogleDrive' || 'trans' || 'new_ctx'
T: '0x406000c'  || 'download'              || 'GoogleDrive' || 'trans' || 'log'
T: '0x806000c'  || 'download'              || 'GoogleDrive' || 'trans' || 'log'
T: '0xc06000c'  || 'download'              || 'GoogleDrive' || 'trans' || 'log'
T: '0x1006000c' || 'download'              || 'GoogleDrive' || 'trans' || 'log'
T: '0x1406000c' || 'download'              || 'GoogleDrive' || 'trans' || 'log'
T: '0x403000c'  || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x803000c'  || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0xc03000c'  || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x1003000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x1403000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x1803000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x1c03000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x2003000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x2403000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x2803000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x2c03000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x3003000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x3403000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x3803000c' || 'view'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x1409000c' || 'start_share'           || 'GoogleDrive' || 'trans' || 'log'
T: '0x409000c'  || 'share'                 || 'GoogleDrive' || 'trans' || 'log'
T: '0x809000c'  || 'unshare'               || 'GoogleDrive' || 'trans' || 'log'
T: '0xc09000c'  || 'share'                 || 'GoogleDrive' || 'trans' || 'log'
-- '0x1009000c' || 'unshare'               || 'GoogleDrive' || 'trans' || 'log'
T: '0x408000c'  || 'delete'                || 'GoogleDrive' || 'trans' || 'log'
T: '0x40b000c'  || 'move'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x808000c'  || 'delete'                || 'GoogleDrive' || 'trans' || 'log'
T: '0x80b000c'  || 'move'                  || 'GoogleDrive' || 'trans' || 'log'
T: '0x407000c'  || 'create_folder'         || 'GoogleDrive' || 'trans' || 'log'
T: '0x807000c'  || 'create_presentation'   || 'GoogleDrive' || 'trans' || 'log'
T: '0xc07000c'  || 'create_document'       || 'GoogleDrive' || 'trans' || 'log'
T: '0x1007000c' || 'create_spreadsheets'   || 'GoogleDrive' || 'trans' || 'log'
T: '0x40c000c'  || 'rename'                || 'GoogleDrive' || 'trans' || 'log'
T: '0x80c000c'  || 'rename'                || 'GoogleDrive' || 'trans' || 'log'
T: '0x1407000c' || 'create_document'       || 'GoogleDrive' || 'trans' || 'log'
T: '0x1807000c' || 'create_spreadsheet'    || 'GoogleDrive' || 'trans' || 'log'
T: '0x1c07000c' || 'create_folder'         || 'GoogleDrive' || 'trans' || 'log'

-- sig_id       || name            || appname               || scope   || action       || append            || desc
T: '0x401000d'  || 'login'         || 'Evernote'            || 'trans' || 'log'
T: '0x801000d'  || 'web_login'     || 'Evernote'            || 'trans' || 'log'
T: '0x402000d'  || 'logout'        || 'Evernote'            || 'trans' || 'log'

-- sig_id       || name            || appname               || scope   || action       || append            || desc
T: '0x401000e'  || 'login'         || 'Github'              || 'trans' || 'log'
T: '0x801000e'  || 'login'         || 'Github'              || 'trans' || 'log'
T: '0xc01000e'  || 'app_login'     || 'Github'              || 'trans' || 'log'
T: '0x402000e'  || 'logout'        || 'Github'              || 'trans' || 'log'

-- sig_id       || name            || appname               || scope   || action       || append            || desc
T: '0x401000f'  || 'login'         || 'Concursolutions'     || 'trans' || 'login_log'
T: '0x402000f'  || 'logout'        || 'Concursolutions'     || 'trans' || 'logout_log'

-- sig_id       || name            || appname               || scope   || action       || append            || desc
T: '0x4010010'  || 'login'         || 'Linkedin'            || 'trans' || 'log'
T: '0x8010010'  || 'login'         || 'Linkedin'            || 'trans' || 'log'
T: '0x4020010'  || 'logout'        || 'Linkedin'            || 'trans' || 'log'

-- sig_id       || name            || appname               || scope   || action       || append            || desc
T: '0x4010013'  || 'login'         || 'Amazon Web Services' || 'trans' || 'log'        || '"success":true'
T: '0x8010013'  || 'login'         || 'Amazon Web Services' || 'trans' || 'log'        || '"success":false'

-- sig_id       || name            || appname               || scope   || action       || append            || desc
T: '0x4010014'  || 'login'         || 'Baidu'               || 'trans' || 'log'        || '"success":true'
T: '0x8010014'  || 'login'         || 'Baidu'               || 'trans' || 'log'        || '"success":true'

-- sig_id       || name        || appname          || scope   || action || append            || desc
T: '0x4010015'  || 'login'     || 'Mail'           || 'trans' || 'log'
T: '0x4010016'  || 'login'     || 'Facebook'       || 'trans' || 'log'  || '"success":true'
T: '0x4010017'  || 'login'     || 'Twitter'        || 'trans' || 'log'  || '"success":true'
T: '0x4010018'  || 'login'     || 'Taobao'         || 'trans' || 'log'  || '"success":true'
T: '0x4010019'  || 'login'     || 'Office365Mail'  || 'trans' || 'log'
T: '0x8010019'  || 'login'     || 'Office365Mail'  || 'trans' || 'log'
T: '0x4010021'  || 'login'     || 'Yahoo'          || 'trans' || 'log'
T: '0x8010021'  || 'login'     || 'Yahoo'          || 'trans' || 'log'
T: '0x4010022'  || 'login'     || 'Workday'        || 'trans' || 'log'
T: '0x4010024'  || 'login'     || 'NetFlix'        || 'trans' || 'log'  || '"success":true'
T: '0x4010026'  || 'login'     || 'Sina'           || 'trans' || 'log'
T: '0x8010026'  || 'login'     || 'Sina'           || 'trans' || 'log'  || '"success":true'
T: '0x801002b'  || 'login'     || 'Eat24hours'     || 'trans' || 'log'  || '"success":true'
T: '0x401002b'  || 'login'     || 'Eat24hours'     || 'trans' || 'log'  || '"success":true'
T: '0x401002e'  || 'login'     || 'Atlassian'      || 'trans' || 'log'  || '"success":true'
T: '0x801002e'  || 'login'     || 'Atlassian'      || 'trans' || 'log'  || '"success":false'
T: '0x401002f'  || 'login'     || 'Jive'           || 'trans' || 'log'  || '"success":true'
T: '0x801002f'  || 'login'     || 'Jive'           || 'trans' || 'log'  || '"success":false'
T: '0x4010030'  || 'login'     || 'Zendesk'        || 'trans' || 'log'  || '"success":true'
T: '0x8010030'  || 'login'     || 'Zendesk'        || 'trans' || 'log'  || '"success":false'
T: '0x4010031'  || 'login'     || 'MySpace'        || 'trans' || 'log'  || '"success":true'
T: '0x8010031'  || 'login'     || 'MySpace'        || 'trans' || 'log'  || '"success":false'
T: '0x4010032'  || 'login'     || 'Yammer'         || 'trans' || 'log'  || '"success":true'
T: '0x8010032'  || 'login'     || 'Yammer'         || 'trans' || 'log'  || '"success":false'
T: '0xc010032'  || 'login'     || 'Yammer'         || 'trans' || 'log'  || '"success":true'
T: '0x4010033'  || 'login'     || 'Godaddy'        || 'trans' || 'log'  || '"success":true'
T: '0x8010033'  || 'login'     || 'Godaddy'        || 'trans' || 'log'  || '"success":false'
T: '0x4010034'  || 'login'     || 'Pinterest'      || 'trans' || 'log'  || '"success":true'
T: '0x8010034'  || 'login'     || 'Pinterest'      || 'trans' || 'log'  || '"success":false'
T: '0x4010035'  || 'login'     || 'Tumblr'         || 'trans' || 'log'  || '"success":true'
T: '0x8010035'  || 'login'     || 'Tumblr'         || 'trans' || 'log'  || '"success":false'
T: '0x4010036'  || 'login'     || 'Docusign'       || 'trans' || 'log'  || '"success":true'
T: '0x8010036'  || 'login'     || 'Docusign'       || 'trans' || 'log'  || '"success":false'
T: '0xc010036'  || 'login'     || 'Docusign'       || 'trans' || 'log'  || '"success":true'
T: '0x10010036' || 'login'     || 'Docusign'       || 'trans' || 'log'  || '"success":false'
T: '0x4010037'  || 'login'     || 'Cisco WebEx'    || 'trans' || 'log'  || '"success":true'
T: '0x8010037'  || 'login'     || 'Cisco WebEx'    || 'trans' || 'log'  || '"success":false'
T: '0x4010038'  || 'login'     || 'Citrix Online'  || 'trans' || 'log'  || '"success":true'
T: '0x8010038'  || 'login'     || 'Citrix Online'  || 'trans' || 'log'  || '"success":false'
T: '0x4010039'  || 'login'     || 'Instagram'      || 'trans' || 'log'  || '"success":true'
T: '0x8010039'  || 'login'     || 'Instagram'      || 'trans' || 'log'  || '"success":false'
T: '0x401003a'  || 'login'     || 'Adobe'          || 'trans' || 'log'  || '"success":true'
T: '0x801003a'  || 'login'     || 'Adobe'          || 'trans' || 'log'  || '"success":false'
T: '0x401003b'  || 'login'     || 'Holonet'        || 'trans' || 'log'  || '"success":true'
T: '0x401003c'  || 'login'     || 'QQ'             || 'trans' || 'log'  || '"success":true'
T: '0x801003c'  || 'mac login' || 'QQ'             || 'trans' || 'log'  || '"success":true'
T: '0x401003d'  || 'login'     || 'Net Ease 163'   || 'trans' || 'log'  || '"success":true'
T: '0x401003e'  || 'login'     || 'AliPay'         || 'trans' || 'log'  || '"success":true'
T: '0x401003f'  || 'login'     || '360'            || 'trans' || 'log'  || '"success":true'
T: '0x4010040'  || 'login'     || 'Jianguoyun'     || 'trans' || 'log'  || '"success":true'
T: '0x8010040'  || 'login'     || 'Jianguoyun'     || 'trans' || 'log'  || '"success":true'
T: '0x4010041'  || 'login'     || 'SpiceWorks'     || 'trans' || 'log'  || '"success":true'
T: '0x8010041'  || 'login'     || 'SpiceWorks'     || 'trans' || 'log'  || '"success":true'
T: '0x4010044'  || 'login'     || 'Fangcloud'      || 'trans' || 'log'  || '"success":true'
T: '0x4010046'  || 'login'     || 'JD'             || 'trans' || 'log'  || '"success":true'
T: '0x4010047'  || 'login'     || 'Slack'          || 'trans' || 'log'  || '"success":true'
T: '0x8010047'  || 'login'     || 'Slack'          || 'trans' || 'log'  || '"success":false'
T: '0x4010048'  || 'login'     || 'Fedex'          || 'trans' || 'log'  || '"success":true'
T: '0x4010049'  || 'login'     || 'Gitbook'        || 'trans' || 'log'  || '"success":true'
T: '0x401004a'  || 'login'     || 'Zhihu'          || 'trans' || 'log'  || '"success":true'
T: '0x801004a'  || 'login'     || 'Zhihu'          || 'trans' || 'log'  || '"success":false'
T: '0x401004b'  || 'login'     || 'Sangfor'        || 'trans' || 'log'  || '"success":true'
T: '0x801004b'  || 'login'     || 'Sangfor'        || 'trans' || 'log'  || '"success":false'
T: '0x401004c'  || 'login'     || 'CSDN'           || 'trans' || 'log'  || '"success":true'
T: '0x4010400'  || 'login'     || 'GoogleCalendar' || 'trans' || 'log'

-- sig_id      || name            || appname          || scope   || action    || append || desc
T: '0xc050045' || 'create_upload' || 'Baidu Cloud'    || 'trans' || 'new_ctx'
T: '0x40d04b7' || 'mail_send'     || 'Google Mail'    || 'trans' || 'log'
T: '0x3ff0029' || 'restful'       || 'Office365 Mail' || 'trans' || 'log'
T: '0x3ff0043' || 'restful'       || 'Litmos'         || 'trans' || 'log'
